const products = [
  {
    id: 1,
    title: "Aria Solitaire Ring",
    category: "Rings",
    price: 189,
    thumbnail: "/img/ring 1.jpeg",
    images: ["/img/ring 1.jpeg"],
    description:
      "خاتم سوليتير أنيق مصنوع يدويًا بتفاصيل دقيقة، مثالي للإطلالات اليومية والمناسبات.",
    brand: "Maison & Luxe",
    weight: "3.2g",
    rating: 4.8,
    stock: 12,
    badge: "New",
  },
  {
    id: 2,
    title: "Verona Twist Band",
    category: "Rings",
    price: 145,
    thumbnail: "/img/ring 2.jpeg",
    images: ["/img/ring 2.jpeg"],
    description: "خاتم بتصميم ملتوي كلاسيكي، خفيف ومريح للاستخدام اليومي.",
    brand: "Maison & Luxe",
    weight: "2.8g",
    rating: 4.6,
    stock: 20,
  },
  {
    id: 3,
    title: "Celeste Diamond Necklace",
    category: "Necklaces",
    price: 310,
    thumbnail: "/img/necklace 1.jpg",
    images: ["/img/necklace 1.jpg"],
    description: "قلادة فاخرة بتفاصيل لامعة، قطعة مثالية للمناسبات الخاصة.",
    brand: "Maison & Luxe",
    weight: "5.1g",
    rating: 4.9,
    stock: 8,
    badge: "Bestseller",
  },
  {
    id: 4,
    title: "Luna Moonstone Necklace",
    category: "Necklaces",
    price: 220,
    thumbnail: "/img/necklace 2.jpg",
    images: ["/img/necklace 2.jpg"],
    description: "قلادة بحجر مونستون هادئ اللون، تناسب الإطلالة الكلاسيكية والعصرية.",
    brand: "Maison & Luxe",
    weight: "4.4g",
    rating: 4.7,
    stock: 15,
    badge: "New",
  },
  {
    id: 5,
    title: "Halo Bangle Stack",
    category: "Bracelets",
    price: 165,
    thumbnail: "/img/braelet 1.jpeg",
    images: ["/img/braelet 1.jpeg"],
    description: "سوار بتصميم متعدد الطبقات، يعطي مظهر أنيق عند تنسيقه مع أساور تانية.",
    brand: "Maison & Luxe",
    weight: "6.0g",
    rating: 4.5,
    stock: 18,
  },
  {
    id: 6,
    title: "Serena Engraved Bangle",
    category: "Bracelets",
    price: 148,
    thumbnail: "/img/bracelet 2.jpg",
    images: ["/img/bracelet 2.jpg"],
    description: "سوار بنقشة يدوية دقيقة، قطعة كلاسيكية تدوم طويلاً.",
    brand: "Maison & Luxe",
    weight: "5.5g",
    rating: 4.6,
    stock: 10,
    badge: "New",
  },
  {
    id: 7,
    title: "Stellar Drop Earrings",
    category: "Earrings",
    price: 96,
    thumbnail: "/img/earring 1.jpg",
    images: ["/img/earring 1.jpg"],
    description: "حلق معلّق بتصميم خفيف، يناسب الاستخدام اليومي والسهرات.",
    brand: "Maison & Luxe",
    weight: "1.8g",
    rating: 4.4,
    stock: 25,
  },
  {
    id: 8,
    title: "Marina Curb Chain",
    category: "Chains",
    price: 225,
    thumbnail: "/img/chain 1.png",
    images: ["/img/chain 1.png"],
    description: "سلسلة كيرب كلاسيكية بتشطيب لامع، تصلح لتنسيقها منفردة أو مع قلادة.",
    brand: "Maison & Luxe",
    weight: "8.2g",
    rating: 4.7,
    stock: 14,
  },
  {
    id: 9,
    title: "Marina Curb Chain",
    category: "Chains",
    price: 225,
    thumbnail: "/img/chain 2.png",
    images: ["/img/chain 2.png"],
    description: "سلسلة كيرب كلاسيكية بتشطيب لامع، تصلح لتنسيقها منفردة أو مع قلادة.",
    brand: "Maison & Luxe",
    weight: "8.2g",
    rating: 4.7,
    stock: 14,
  },
  {
    id: 10,
    title: "Marina Curb Chain",
    category: "Chains",
    price: 225,
    thumbnail: "/img/chain 3.png",
    images: ["/img/chain 3.png"],
    description: "سلسلة كيرب كلاسيكية بتشطيب لامع، تصلح لتنسيقها منفردة أو مع قلادة.",
    brand: "Maison & Luxe",
    weight: "8.2g",
    rating: 4.7,
    stock: 14,
  },
  {
    id: 11,
    title: "Marina Curb Chain",
    category: "Chains",
    price: 225,
    thumbnail: "/img/chain 4.png",
    images: ["/img/chain 4.png"],
    description: "سلسلة كيرب كلاسيكية بتشطيب لامع، تصلح لتنسيقها منفردة أو مع قلادة.",
    brand: "Maison & Luxe",
    weight: "8.2g",
    rating: 4.7,
    stock: 14,
  },
  {
    id: 12,
    title: "Vesper Automatic Watch",
    category: "Watches",
    price: 620,
    thumbnail: "/img/watch 1.jpg",
    images: ["/img/watch 1.jpg"],
    description: "ساعة أوتوماتيك بتصميم بسيط وفاخر، مناسبة للإطلالة الرسمية.",
    brand: "Maison & Luxe",
    weight: "82g",
    rating: 4.9,
    stock: 6,
    badge: "New",
  },
];

export const getProductById = (id) =>
  products.find((p) => String(p.id) === String(id));

export default products;